### ISSUE TITLE
Corruplot in subplot environment

### ISSUE THREAD

**Issue by jsudheer** [biokit/biokit#33]
Dear develpper,
              Is it possible to use corrplot in subplot environment. Is there an easy way?.  Is it possible to get  get a grid of corrplots from different seasons and single colorbar.

from biokit.viz import corrplot
df = pd.DataFrame(dict(( (k, np.random.random(10)+ord(k)-65) for k in letters)))
df = df.corr()
c = corrplot.Corrplot(df)

I wanted to make the corrplot in below 4 boxes which can come out as a single figure. The above data is a test data actually I wanted use seasonal data for this purpose.

fig = plt.figure()
fig.subplots_adjust(left=0.2, wspace=0.6)
ax1 = fig.add_subplot(221)
ax2 = fig.add_subplot(222)
ax3 = fig.add_subplot(223)
ax4 = fig.add_subplot(224)

**Comment by cokelaer** [comment]
This should now be possible with the latest version

![example](https://cloud.githubusercontent.com/assets/778821/7789392/afd32b44-0256-11e5-866c-32fcd4ec021c.png)

  
  from biokit import 
  fig = plt.figure()
  fig.subplots_adjust(left=0.2, wspace=0.6)
  ax1 = fig.add_subplot(221)
  ax2 = fig.add_subplot(222)
  ax3 = fig.add_subplot(223)
  ax4 = fig.add_subplot(224)

  import numpy as np
  c = corrplot.Corrplot(np.random.rand(10,10))
  c.plot(fig=fig, ax=ax3, colorbar=True, cmap='copper', method='rectangle')
  c.plot(fig=fig, ax=ax4, colorbar=True, cmap='jet', method='color')
  c.plot(fig=fig, ax=ax2, colorbar=True, cmap='hot', method='ellipse')
  c.plot(fig=fig, ax=ax1, colorbar=True,  method='pie')
