### ISSUE TITLE
vcf2bed

### ISSUE THREAD

**Issue by khillion** [biokit/biokit#60]
found this tool to perform this convertion: http://bedops.readthedocs.io/en/latest/content/reference/file-management/conversion/vcf2bed.html

**Comment by khillion** [comment]
The use by default of vcf2bed does not deal with insertions and deletions. Specific options need to be used to specifically perform these conversions. Need to find an other tool or code it directly (I think we should go for this option).

**Comment by cokelaer** [comment]
moved to bioconvert
