### ISSUE TITLE
Shouldn't fasta io be idempotent ?

### ISSUE THREAD

**Issue by bryan-brancotte** [biokit/biokit#65]
If the save/load of a fasta fetch from Uniprot be idempotent, we should add a test (and fix it) as for now it is not the case.
Proposing the test in a separated branch

**Comment by bryan-brancotte** [comment]
branch is https://github.com/biokit/biokit/tree/bryan-brancotte-io-idempotency-fasta-issue-65

**Comment by cokelaer** [comment]
merged on the master
